/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dimes_util_comState_CommunicationDetector */

#ifndef _Included_dimes_util_comState_CommunicationDetector
#define _Included_dimes_util_comState_CommunicationDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dimes_util_comState_CommunicationDetector
 * Method:    gotInetrnetConnection
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_dimes_util_comState_CommunicationDetector_gotInetrnetConnection
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
